import type { Hero } from '../../types';

export const mockHeroes: Hero[] = [
  {
    id: 'hero-home',
    title: 'YOUR BRAND. OUR CREATIVE',
    title1: 'ECHO.',
    slug: 'home',
    selectPage: '/',
    smallText: 'Digital Marketing & Content Studio',
    heroDescription: 'A Gen Z-led digital marketing and content production company creating content, campaigns and digital experiences people actually remember.',
    videoUrl: '/assets/hero-section-video1.mp4',
    button1Label: "LET'S MAKE SOME NOISE",
    button1PageLink: '/contact/',
    button2Label: 'SEE THE WORK',
    button2PageLink: '/projects/',
  },
  {
    id: 'hero-about',
    title1: '',
    title: "WE'RE THE GENERATION THAT GREW UP ONLINE.",
    slug: 'about',
    selectPage: '/about/',
    smallText: 'About The Digital Echo',
    heroDescription: "We're a team of creatives, strategists, and storytellers who believe content should make people feel something.",
    videoUrl: '',
    button1Label: 'MEET THE CREW',
    button1PageLink: '/about/',
    button2Label: '',
    button2PageLink: '',
  },
  {
    id: 'hero-contact',
    title1: '',
    title: 'GOT A BRAND THAT NEEDS AN ECHO?',
    slug: 'contact',
    selectPage: '/contact/',
    smallText: "Let's Create Together",
    heroDescription: "Got a brand that needs an echo? Let's talk about your next project.",
    videoUrl: '',
    button1Label: 'WHATSAPP US',
    button1PageLink: 'https://wa.me/919999999999',
    button2Label: '',
    button2PageLink: '',
  },
  {
    id: 'hero-services',
    title1: '',
    title: 'EVERYTHING YOUR BRAND NEEDS TO BE SEEN.',
    slug: 'services',
    selectPage: '/services/',
    smallText: 'Our Services',
    heroDescription: 'Photography, videography, drone shoots, social media management and digital marketing — all under one roof.',
    videoUrl: '',
    button1Label: 'EXPLORE SERVICES',
    button1PageLink: '/services/',
    button2Label: '',
    button2PageLink: '',
  },
  {
    id: 'hero-projects',
    title1: '',
    title: 'WORK > WORDS.',
    slug: 'projects',
    selectPage: '/projects/',
    smallText: 'Our Portfolio',
    heroDescription: 'See what we have created for brands across India.',
    videoUrl: '',
    button1Label: 'VIEW ALL PROJECTS',
    button1PageLink: '/projects/',
    button2Label: '',
    button2PageLink: '',
  },
  {
    id: 'hero-blog',
    title1: '',
    title: 'THE DROP.',
    slug: 'blog',
    selectPage: '/blog/',
    smallText: 'Insights & Stories',
    heroDescription: 'Thoughts, stories, and insights from the world of digital marketing and content creation.',
    videoUrl: '',
    button1Label: '',
    button1PageLink: '',
    button2Label: '',
    button2PageLink: '',
  },
];
