import type { Post } from '../../types';

export const mockPosts: Post[] = [
  {
    id: '1',
    title: 'Why Gen Z Brands Need a Different Approach',
    slug: 'gen-z-brands-different-approach',
    excerpt: "Gen Z doesn't respond to traditional marketing. Here's what works instead.",
    content: "<p>Gen Z is the first generation to grow up entirely in the digital age. They have unique preferences when it comes to brands and marketing.</p><p>Here's what you need to know to connect with them effectively.</p>",
    featuredImage: { node: { sourceUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=630&fit=crop', altText: 'Gen Z Marketing', width: 1200, height: 630 } },
    author: { name: 'The Digital Echo', avatar: { url: '' } },
    categories: [{ name: 'Marketing', slug: 'marketing' }],
    tags: [{ name: 'Gen Z', slug: 'gen-z' }, { name: 'Marketing', slug: 'marketing' }],
    publishedDate: '2026-01-10',
    modifiedDate: '2026-01-10',
    seo: { title: 'Why Gen Z Brands Need a Different Approach', description: 'Gen Z marketing guide.', canonical: 'https://thedigitalecho.com/blog/gen-z-brands-different-approach/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '2',
    title: 'The Power of Visual Content in 2026',
    slug: 'power-of-visual-content-2026',
    excerpt: "Visual content is king. Here's why you need to invest in it.",
    content: "<p>In 2026, visual content is more important than ever. Here's how to make it work for your brand.</p>",
    featuredImage: { node: { sourceUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&h=630&fit=crop', altText: 'Visual Content', width: 1200, height: 630 } },
    author: { name: 'The Digital Echo', avatar: { url: '' } },
    categories: [{ name: 'Content', slug: 'content' }],
    tags: [{ name: 'Visual Content', slug: 'visual-content' }],
    publishedDate: '2026-02-05',
    modifiedDate: '2026-02-05',
    seo: { title: 'Power of Visual Content 2026', description: 'Visual content guide.', canonical: 'https://thedigitalecho.com/blog/power-of-visual-content-2026/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '3',
    title: 'Drone Photography: A Complete Guide',
    slug: 'drone-photography-complete-guide',
    excerpt: 'Everything you need to know about drone photography for your brand.',
    content: "<p>Drone photography has revolutionized how we capture the world. Here's your complete guide.</p>",
    featuredImage: { node: { sourceUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=1200&h=630&fit=crop', altText: 'Drone Photography', width: 1200, height: 630 } },
    author: { name: 'The Digital Echo', avatar: { url: '' } },
    categories: [{ name: 'Photography', slug: 'photography' }],
    tags: [{ name: 'Drone', slug: 'drone' }, { name: 'Photography', slug: 'photography' }],
    publishedDate: '2026-03-15',
    modifiedDate: '2026-03-15',
    seo: { title: 'Drone Photography Guide', description: 'Drone photography guide.', canonical: 'https://thedigitalecho.com/blog/drone-photography-complete-guide/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
];
