import type { Project } from '../../types';

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'Brand Refresh for TechStart',
    slug: 'techstart-brand-refresh',
    clientName: 'TechStart',
    clientLogo: { node: { sourceUrl: 'https://via.placeholder.com/200x60/080808/C8FF00?text=TechStart', altText: 'TechStart', width: 200, height: 60 } },
    heroImage: { node: { sourceUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=1600&h=900&fit=crop', altText: 'TechStart Project', width: 1600, height: 900 } },
    gallery: [],
    video: '',
    category: ['Branding', 'Social Media'],
    servicesUsed: ['Content Production', 'Social Media Management'],
    challenge: 'TechStart needed a complete brand overhaul to appeal to a younger demographic.',
    strategy: 'We developed a bold, modern visual identity with Gen Z-friendly messaging.',
    execution: 'Created 50+ content pieces, managed social media for 3 months.',
    result: '300% increase in social media engagement, 150% growth in followers.',
    testimonial: 'The Digital Echo completely transformed our brand.',
    testimonialAuthor: 'Priya Sharma',
    testimonialCompany: 'TechStart',
    projectDate: '2026-01-15',
    location: 'Mumbai',
    featured: true,
    seo: { title: 'TechStart Brand Refresh | The Digital Echo', description: 'How The Digital Echo transformed TechStart.', canonical: 'https://thedigitalecho.com/projects/techstart-brand-refresh/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '2',
    title: 'Social Campaign for FreshBite',
    slug: 'freshbite-social-campaign',
    clientName: 'FreshBite',
    clientLogo: { node: { sourceUrl: 'https://via.placeholder.com/200x60/080808/C8FF00?text=FreshBite', altText: 'FreshBite', width: 200, height: 60 } },
    heroImage: { node: { sourceUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1600&h=900&fit=crop', altText: 'FreshBite Campaign', width: 1600, height: 900 } },
    gallery: [],
    video: '',
    category: ['Social Media', 'Campaigns'],
    servicesUsed: ['Social Media Management', 'Photography', 'Videography'],
    challenge: 'FreshBite wanted to increase brand awareness among food enthusiasts.',
    strategy: 'We created a content-first strategy with stunning food photography.',
    execution: 'Produced 100+ content pieces, ran targeted ad campaigns.',
    result: '500% increase in Instagram engagement, 200% increase in orders.',
    testimonial: 'Our social media went from zero to hero.',
    testimonialAuthor: 'Rahul Verma',
    testimonialCompany: 'FreshBite',
    projectDate: '2026-02-20',
    location: 'Pune',
    featured: true,
    seo: { title: 'FreshBite Campaign | The Digital Echo', description: 'FreshBite social media campaign.', canonical: 'https://thedigitalecho.com/projects/freshbite-social-campaign/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '3',
    title: 'Drone Campaign for BuildRight',
    slug: 'buildright-drone-campaign',
    clientName: 'BuildRight',
    clientLogo: { node: { sourceUrl: 'https://via.placeholder.com/200x60/080808/C8FF00?text=BuildRight', altText: 'BuildRight', width: 200, height: 60 } },
    heroImage: { node: { sourceUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1600&h=900&fit=crop', altText: 'BuildRight Drone', width: 1600, height: 900 } },
    gallery: [],
    video: '',
    category: ['Drone', 'Corporate'],
    servicesUsed: ['Drone Photography', 'Drone Videography'],
    challenge: 'BuildRight needed to showcase their construction projects from unique angles.',
    strategy: 'We used drone photography and videography to capture stunning aerial views.',
    execution: 'Filmed 20+ construction sites over 2 months.',
    result: 'Won industry award for best construction marketing campaign.',
    testimonial: 'The drone footage changed how we present our work.',
    testimonialAuthor: 'Amit Patel',
    testimonialCompany: 'BuildRight',
    projectDate: '2026-03-10',
    location: 'Delhi',
    featured: true,
    seo: { title: 'BuildRight Drone Campaign | The Digital Echo', description: 'BuildRight drone marketing.', canonical: 'https://thedigitalecho.com/projects/buildright-drone-campaign/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '4',
    title: 'E-commerce for StyleHub',
    slug: 'stylehub-ecommerce',
    clientName: 'StyleHub',
    clientLogo: { node: { sourceUrl: 'https://via.placeholder.com/200x60/080808/C8FF00?text=StyleHub', altText: 'StyleHub', width: 200, height: 60 } },
    heroImage: { node: { sourceUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1600&h=900&fit=crop', altText: 'StyleHub', width: 1600, height: 900 } },
    gallery: [],
    video: '',
    category: ['Ecommerce', 'Photography'],
    servicesUsed: ['Photography', 'Digital Marketing', 'Social Media Management'],
    challenge: 'StyleHub needed to increase online sales through better content and marketing.',
    strategy: 'We created a comprehensive content and digital marketing strategy.',
    execution: 'Shot 500+ product images, ran Google and Meta ad campaigns.',
    result: '400% increase in online sales within 6 months.',
    testimonial: 'Our online sales have never been better.',
    testimonialAuthor: 'Neha Gupta',
    testimonialCompany: 'StyleHub',
    projectDate: '2026-04-05',
    location: 'Mumbai',
    featured: false,
    seo: { title: 'StyleHub E-commerce | The Digital Echo', description: 'StyleHub e-commerce project.', canonical: 'https://thedigitalecho.com/projects/stylehub-ecommerce/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
];
