import type { ContentSection, Service } from '../../types';

const caps = (...names: string[]): ContentSection[] => [
  { heading: 'Capabilities', paragraphs: [], items: names.map((text) => ({ text })) },
];

export const mockServices: Service[] = [
  {
    id: '1',
    title: 'Content Production',
    slug: 'content-production',
    shortDescription: 'Photography, videography, and brand content that stops the scroll.',
    description: 'We create visual stories that make people stop scrolling.',
    heroTitle: 'CONTENT THAT STOPS THE SCROLL.',
    heroDescription: 'Professional photography and videography for brands.',
    featuredImage: {
      node: {
        sourceUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1600&h=900&fit=crop',
        altText: 'Content Production',
        width: 1600,
        height: 900,
      },
    },
    gallery: [],
    icon: '📸',
    serviceCategory: 'content',
    sections: caps('Photography', 'Videography', 'Brand Content', 'Product Photography'),
    process: ['Strategy', 'Concept', 'Production', 'Delivery'],
    pageCta: null,
    seo: { title: 'Content Production | The Digital Echo', description: 'Content production services.', canonical: 'https://thedigitalecho.com/services/content-production/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '2',
    title: 'Photography',
    slug: 'photography',
    shortDescription: 'Visual storytelling through the lens.',
    description: 'Every brand has a story. We tell it through striking photography.',
    heroTitle: 'VISUAL STORIES THAT SPEAK.',
    heroDescription: 'Professional photography for brands.',
    featuredImage: {
      node: {
        sourceUrl: 'https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=1600&h=900&fit=crop',
        altText: 'Photography',
        width: 1600,
        height: 900,
      },
    },
    gallery: [],
    icon: '📷',
    serviceCategory: 'content',
    sections: caps('Product Photography', 'Lifestyle', 'Corporate', 'Events'),
    process: ['Brief', 'Shoot', 'Edit', 'Deliver'],
    pageCta: null,
    seo: { title: 'Photography | The Digital Echo', description: 'Photography services.', canonical: 'https://thedigitalecho.com/services/photography/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '3',
    title: 'Videography',
    slug: 'videography',
    shortDescription: 'Cinematic video content for digital platforms.',
    description: 'From brand films to social reels, we create video content.',
    heroTitle: 'VIDEOS THAT MOVE PEOPLE.',
    heroDescription: 'Cinematic videography for the digital age.',
    featuredImage: {
      node: {
        sourceUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1600&h=900&fit=crop',
        altText: 'Videography',
        width: 1600,
        height: 900,
      },
    },
    gallery: [],
    icon: '🎬',
    serviceCategory: 'content',
    sections: caps('Brand Films', 'Social Reels', 'Corporate Videos', 'Ads'),
    process: ['Concept', 'Script', 'Shoot', 'Edit', 'Delivery'],
    pageCta: null,
    seo: { title: 'Videography | The Digital Echo', description: 'Videography services.', canonical: 'https://thedigitalecho.com/services/videography/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '4',
    title: 'Drone Photography',
    slug: 'drone-photography',
    shortDescription: 'Aerial perspectives that change the game.',
    description: 'Drone photography that reveals your brand from a new angle.',
    heroTitle: 'CHANGE THE PERSPECTIVE.',
    heroDescription: 'Aerial photography for brands.',
    featuredImage: {
      node: {
        sourceUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=1600&h=900&fit=crop',
        altText: 'Drone Photography',
        width: 1600,
        height: 900,
      },
    },
    gallery: [],
    icon: '🚁',
    serviceCategory: 'drone',
    sections: caps('Aerial Photography', 'Real Estate', 'Events', 'Construction'),
    process: ['Survey', 'Flight', 'Capture', 'Process'],
    pageCta: null,
    seo: { title: 'Drone Photography | The Digital Echo', description: 'Drone photography services.', canonical: 'https://thedigitalecho.com/services/drone-photography/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '5',
    title: 'Drone Videography',
    slug: 'drone-videography',
    shortDescription: 'Cinematic aerial video content.',
    description: 'Cinematic drone footage that takes your brand to new heights.',
    heroTitle: 'FLY ABOVE THE NOISE.',
    heroDescription: 'Aerial videography for brands.',
    featuredImage: {
      node: {
        sourceUrl: 'https://images.unsplash.com/photo-1506947411487-a56738267384?w=1600&h=900&fit=crop',
        altText: 'Drone Videography',
        width: 1600,
        height: 900,
      },
    },
    gallery: [],
    icon: '🛩️',
    serviceCategory: 'drone',
    sections: caps('Aerial Video', 'Site Surveys', 'Promotional', 'Events'),
    process: ['Plan', 'Fly', 'Capture', 'Edit'],
    pageCta: null,
    seo: { title: 'Drone Videography | The Digital Echo', description: 'Drone videography services.', canonical: 'https://thedigitalecho.com/services/drone-videography/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '6',
    title: 'Social Media Management',
    slug: 'social-media-management',
    shortDescription: 'Your feed called. It wants better content.',
    description: 'We manage your social media so you can focus on what you do best.',
    heroTitle: 'YOUR FEED CALLED. IT WANTS BETTER CONTENT.',
    heroDescription: 'Social media management that works.',
    featuredImage: {
      node: {
        sourceUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1600&h=900&fit=crop',
        altText: 'Social Media Management',
        width: 1600,
        height: 900,
      },
    },
    gallery: [],
    icon: '📱',
    serviceCategory: 'social',
    sections: caps('Instagram', 'Facebook', 'LinkedIn', 'YouTube', 'WhatsApp'),
    process: ['Audit', 'Strategy', 'Content', 'Publish', 'Analyze'],
    pageCta: null,
    seo: { title: 'Social Media Management | The Digital Echo', description: 'Social media management.', canonical: 'https://thedigitalecho.com/services/social-media-management/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '7',
    title: 'Digital Marketing',
    slug: 'digital-marketing',
    shortDescription: 'Marketing that actually converts.',
    description: 'Data-driven digital marketing that puts your brand in front of the right people.',
    heroTitle: 'MARKETING THAT MATTERS.',
    heroDescription: 'Digital marketing that drives results.',
    featuredImage: {
      node: {
        sourceUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&h=900&fit=crop',
        altText: 'Digital Marketing',
        width: 1600,
        height: 900,
      },
    },
    gallery: [],
    icon: '📊',
    serviceCategory: 'marketing',
    sections: caps('Google Ads', 'Meta Ads', 'LinkedIn Ads', 'Analytics'),
    process: ['Research', 'Strategy', 'Execute', 'Optimize'],
    pageCta: null,
    seo: { title: 'Digital Marketing | The Digital Echo', description: 'Digital marketing services.', canonical: 'https://thedigitalecho.com/services/digital-marketing/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
  {
    id: '8',
    title: 'SEO',
    slug: 'seo',
    shortDescription: 'Be found when it matters.',
    description: 'Search engine optimization that gets your brand to the top of Google.',
    heroTitle: 'BE FOUND. BE CHOSEN.',
    heroDescription: 'SEO that drives organic growth.',
    featuredImage: {
      node: {
        sourceUrl: 'https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=1600&h=900&fit=crop',
        altText: 'SEO',
        width: 1600,
        height: 900,
      },
    },
    gallery: [],
    icon: '🔍',
    serviceCategory: 'marketing',
    sections: caps('Technical SEO', 'Content Strategy', 'Link Building', 'Local SEO'),
    process: ['Audit', 'Strategy', 'Implement', 'Monitor'],
    pageCta: null,
    seo: { title: 'SEO Services | The Digital Echo', description: 'SEO services.', canonical: 'https://thedigitalecho.com/services/seo/', ogImage: '', ogTitle: '', ogDescription: '', twitterTitle: '', twitterDescription: '', twitterImage: '' },
  },
];
